CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Expenses created before auth existed cannot be attributed to any user.
DELETE FROM expenses;

ALTER TABLE expenses ADD COLUMN user_id BIGINT NOT NULL;
ALTER TABLE expenses ADD CONSTRAINT fk_expenses_user FOREIGN KEY (user_id) REFERENCES users (id);
CREATE INDEX idx_expenses_user ON expenses (user_id);
