CREATE TABLE budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    category VARCHAR(30) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    CONSTRAINT fk_budgets_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_budgets_user_category UNIQUE (user_id, category)
);

CREATE TABLE recurring_expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    category VARCHAR(30) NOT NULL,
    note VARCHAR(500),
    day_of_month INT NOT NULL,
    next_run DATE NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_recurring_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_budgets_user ON budgets (user_id);
CREATE INDEX idx_recurring_user ON recurring_expenses (user_id);
CREATE INDEX idx_recurring_next_run ON recurring_expenses (next_run);
